// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// llikBetaInternal
Rcpp::DataFrame llikBetaInternal(Rcpp::NumericVector x, Rcpp::NumericVector shape1, Rcpp::NumericVector shape2);
RcppExport SEXP _rxode2ll_llikBetaInternal(SEXP xSEXP, SEXP shape1SEXP, SEXP shape2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shape2(shape2SEXP);
    rcpp_result_gen = Rcpp::wrap(llikBetaInternal(x, shape1, shape2));
    return rcpp_result_gen;
END_RCPP
}
// llikBetaProportionInternal
Rcpp::DataFrame llikBetaProportionInternal(Rcpp::NumericVector x, Rcpp::NumericVector mu, Rcpp::NumericVector kappa);
RcppExport SEXP _rxode2ll_llikBetaProportionInternal(SEXP xSEXP, SEXP muSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikBetaProportionInternal(x, mu, kappa));
    return rcpp_result_gen;
END_RCPP
}
// llikBinomInternal
Rcpp::DataFrame llikBinomInternal(Rcpp::NumericVector x, Rcpp::NumericVector size, Rcpp::NumericVector prob);
RcppExport SEXP _rxode2ll_llikBinomInternal(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(llikBinomInternal(x, size, prob));
    return rcpp_result_gen;
END_RCPP
}
// llikCauchyInternal
Rcpp::DataFrame llikCauchyInternal(Rcpp::NumericVector x, Rcpp::NumericVector location, Rcpp::NumericVector scale);
RcppExport SEXP _rxode2ll_llikCauchyInternal(SEXP xSEXP, SEXP locationSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type location(locationSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(llikCauchyInternal(x, location, scale));
    return rcpp_result_gen;
END_RCPP
}
// llikChisqInternal
Rcpp::DataFrame llikChisqInternal(Rcpp::NumericVector x, Rcpp::NumericVector df);
RcppExport SEXP _rxode2ll_llikChisqInternal(SEXP xSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(llikChisqInternal(x, df));
    return rcpp_result_gen;
END_RCPP
}
// llikDblExpInternal
Rcpp::DataFrame llikDblExpInternal(Rcpp::NumericVector x, Rcpp::NumericVector mu, Rcpp::NumericVector sigma);
RcppExport SEXP _rxode2ll_llikDblExpInternal(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikDblExpInternal(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// llikExpInternal
Rcpp::DataFrame llikExpInternal(Rcpp::NumericVector x, Rcpp::NumericVector rate);
RcppExport SEXP _rxode2ll_llikExpInternal(SEXP xSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(llikExpInternal(x, rate));
    return rcpp_result_gen;
END_RCPP
}
// llikFInternal
Rcpp::DataFrame llikFInternal(Rcpp::NumericVector x, Rcpp::NumericVector df1, Rcpp::NumericVector df2);
RcppExport SEXP _rxode2ll_llikFInternal(SEXP xSEXP, SEXP df1SEXP, SEXP df2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type df1(df1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type df2(df2SEXP);
    rcpp_result_gen = Rcpp::wrap(llikFInternal(x, df1, df2));
    return rcpp_result_gen;
END_RCPP
}
// llikFrechetInternal
Rcpp::DataFrame llikFrechetInternal(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector sigma);
RcppExport SEXP _rxode2ll_llikFrechetInternal(SEXP xSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikFrechetInternal(x, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// llikGammaInternal
Rcpp::DataFrame llikGammaInternal(Rcpp::NumericVector x, Rcpp::NumericVector shape, Rcpp::NumericVector rate);
RcppExport SEXP _rxode2ll_llikGammaInternal(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(llikGammaInternal(x, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// llikGeomInternal
Rcpp::DataFrame llikGeomInternal(Rcpp::NumericVector x, Rcpp::NumericVector p);
RcppExport SEXP _rxode2ll_llikGeomInternal(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(llikGeomInternal(x, p));
    return rcpp_result_gen;
END_RCPP
}
// llikGumbelInternal
Rcpp::DataFrame llikGumbelInternal(Rcpp::NumericVector x, Rcpp::NumericVector mu, Rcpp::NumericVector beta);
RcppExport SEXP _rxode2ll_llikGumbelInternal(SEXP xSEXP, SEXP muSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikGumbelInternal(x, mu, beta));
    return rcpp_result_gen;
END_RCPP
}
// llikInvChisqInternal
Rcpp::DataFrame llikInvChisqInternal(Rcpp::NumericVector x, Rcpp::NumericVector nu);
RcppExport SEXP _rxode2ll_llikInvChisqInternal(SEXP xSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(llikInvChisqInternal(x, nu));
    return rcpp_result_gen;
END_RCPP
}
// llikInvGammaInternal
Rcpp::DataFrame llikInvGammaInternal(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector beta);
RcppExport SEXP _rxode2ll_llikInvGammaInternal(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikInvGammaInternal(x, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// llikLnormInternal
Rcpp::DataFrame llikLnormInternal(Rcpp::NumericVector x, Rcpp::NumericVector meanlog, Rcpp::NumericVector sdlog);
RcppExport SEXP _rxode2ll_llikLnormInternal(SEXP xSEXP, SEXP meanlogSEXP, SEXP sdlogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type meanlog(meanlogSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sdlog(sdlogSEXP);
    rcpp_result_gen = Rcpp::wrap(llikLnormInternal(x, meanlog, sdlog));
    return rcpp_result_gen;
END_RCPP
}
// llikLogisInternal
Rcpp::DataFrame llikLogisInternal(Rcpp::NumericVector x, Rcpp::NumericVector location, Rcpp::NumericVector scale);
RcppExport SEXP _rxode2ll_llikLogisInternal(SEXP xSEXP, SEXP locationSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type location(locationSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(llikLogisInternal(x, location, scale));
    return rcpp_result_gen;
END_RCPP
}
// llikNbinomInternal
Rcpp::DataFrame llikNbinomInternal(Rcpp::NumericVector x, Rcpp::NumericVector size, Rcpp::NumericVector prob);
RcppExport SEXP _rxode2ll_llikNbinomInternal(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(llikNbinomInternal(x, size, prob));
    return rcpp_result_gen;
END_RCPP
}
// llikNbinomMuInternal
Rcpp::DataFrame llikNbinomMuInternal(Rcpp::NumericVector x, Rcpp::NumericVector size, Rcpp::NumericVector mu);
RcppExport SEXP _rxode2ll_llikNbinomMuInternal(SEXP xSEXP, SEXP sizeSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(llikNbinomMuInternal(x, size, mu));
    return rcpp_result_gen;
END_RCPP
}
// llikNormInternal
Rcpp::DataFrame llikNormInternal(Rcpp::NumericVector x, Rcpp::NumericVector mu, Rcpp::NumericVector sigma);
RcppExport SEXP _rxode2ll_llikNormInternal(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikNormInternal(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// llikParetoInternal
Rcpp::DataFrame llikParetoInternal(Rcpp::NumericVector x, Rcpp::NumericVector yMin, Rcpp::NumericVector alpha);
RcppExport SEXP _rxode2ll_llikParetoInternal(SEXP xSEXP, SEXP yMinSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yMin(yMinSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikParetoInternal(x, yMin, alpha));
    return rcpp_result_gen;
END_RCPP
}
// llikParetoType2Internal
Rcpp::DataFrame llikParetoType2Internal(Rcpp::NumericVector x, Rcpp::NumericVector mu, Rcpp::NumericVector lambda, Rcpp::NumericVector alpha);
RcppExport SEXP _rxode2ll_llikParetoType2Internal(SEXP xSEXP, SEXP muSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikParetoType2Internal(x, mu, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// llikPoisInternal
Rcpp::DataFrame llikPoisInternal(Rcpp::NumericVector x, Rcpp::NumericVector lambda);
RcppExport SEXP _rxode2ll_llikPoisInternal(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikPoisInternal(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// llikRayleighInternal
Rcpp::DataFrame llikRayleighInternal(Rcpp::NumericVector x, Rcpp::NumericVector sigma);
RcppExport SEXP _rxode2ll_llikRayleighInternal(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikRayleighInternal(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// llikScaledInvChisqInternal
Rcpp::DataFrame llikScaledInvChisqInternal(Rcpp::NumericVector x, Rcpp::NumericVector nu, Rcpp::NumericVector sigma);
RcppExport SEXP _rxode2ll_llikScaledInvChisqInternal(SEXP xSEXP, SEXP nuSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikScaledInvChisqInternal(x, nu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// llikTInternal
Rcpp::DataFrame llikTInternal(Rcpp::NumericVector x, Rcpp::NumericVector df, Rcpp::NumericVector mean, Rcpp::NumericVector sd);
RcppExport SEXP _rxode2ll_llikTInternal(SEXP xSEXP, SEXP dfSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(llikTInternal(x, df, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// llikUnifInternal
Rcpp::DataFrame llikUnifInternal(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector beta);
RcppExport SEXP _rxode2ll_llikUnifInternal(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(llikUnifInternal(x, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// llikWeibullInternal
Rcpp::DataFrame llikWeibullInternal(Rcpp::NumericVector x, Rcpp::NumericVector shape, Rcpp::NumericVector scale);
RcppExport SEXP _rxode2ll_llikWeibullInternal(SEXP xSEXP, SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(llikWeibullInternal(x, shape, scale));
    return rcpp_result_gen;
END_RCPP
}
