# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llikBetaInternal <- function(x, shape1, shape2) {
    .Call(`_rxode2ll_llikBetaInternal`, x, shape1, shape2)
}

llikBinomInternal <- function(x, size, prob) {
    .Call(`_rxode2ll_llikBinomInternal`, x, size, prob)
}

llikCauchyInternal <- function(x, location, scale) {
    .Call(`_rxode2ll_llikCauchyInternal`, x, location, scale)
}

llikChisqInternal <- function(x, df) {
    .Call(`_rxode2ll_llikChisqInternal`, x, df)
}

llikExpInternal <- function(x, rate) {
    .Call(`_rxode2ll_llikExpInternal`, x, rate)
}

llikFInternal <- function(x, df1, df2) {
    .Call(`_rxode2ll_llikFInternal`, x, df1, df2)
}

llikGammaInternal <- function(x, shape, rate) {
    .Call(`_rxode2ll_llikGammaInternal`, x, shape, rate)
}

llikGeomInternal <- function(x, p) {
    .Call(`_rxode2ll_llikGeomInternal`, x, p)
}

llikNbinomInternal <- function(x, size, prob) {
    .Call(`_rxode2ll_llikNbinomInternal`, x, size, prob)
}

llikNbinomMuInternal <- function(x, size, mu) {
    .Call(`_rxode2ll_llikNbinomMuInternal`, x, size, mu)
}

llikNormInternal <- function(x, mu, sigma) {
    .Call(`_rxode2ll_llikNormInternal`, x, mu, sigma)
}

llikPoisInternal <- function(x, lambda) {
    .Call(`_rxode2ll_llikPoisInternal`, x, lambda)
}

llikTInternal <- function(x, df, mean, sd) {
    .Call(`_rxode2ll_llikTInternal`, x, df, mean, sd)
}

llikUnifInternal <- function(x, alpha, beta) {
    .Call(`_rxode2ll_llikUnifInternal`, x, alpha, beta)
}

llikWeibullInternal <- function(x, shape, scale) {
    .Call(`_rxode2ll_llikWeibullInternal`, x, shape, scale)
}

